// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ZckjJ3Ren4IQnfoaiwqLMCk_cWTfKTI',
    appId: '1:882740307482:web:252521a8ba6a3db93e53a3',
    messagingSenderId: '882740307482',
    projectId: 'healthtrack-app-7dc6d',
    authDomain: 'healthtrack-app-7dc6d.firebaseapp.com',
    storageBucket: 'healthtrack-app-7dc6d.firebasestorage.app',
    measurementId: 'G-R70S2P3V8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwH2fAMVrD5hvo4fFG5LAlLDg7U7_8Rr8',
    appId: '1:882740307482:android:ac5f72d27b1e74803e53a3',
    messagingSenderId: '882740307482',
    projectId: 'healthtrack-app-7dc6d',
    storageBucket: 'healthtrack-app-7dc6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_AssM63ZwFjzqFItY2fooDmFtzUNPFJ0',
    appId: '1:882740307482:ios:14e749fb3c07b4f63e53a3',
    messagingSenderId: '882740307482',
    projectId: 'healthtrack-app-7dc6d',
    storageBucket: 'healthtrack-app-7dc6d.firebasestorage.app',
    iosBundleId: 'com.example.healthtrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_AssM63ZwFjzqFItY2fooDmFtzUNPFJ0',
    appId: '1:882740307482:ios:14e749fb3c07b4f63e53a3',
    messagingSenderId: '882740307482',
    projectId: 'healthtrack-app-7dc6d',
    storageBucket: 'healthtrack-app-7dc6d.firebasestorage.app',
    iosBundleId: 'com.example.healthtrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ZckjJ3Ren4IQnfoaiwqLMCk_cWTfKTI',
    appId: '1:882740307482:web:a234e0417a8da8163e53a3',
    messagingSenderId: '882740307482',
    projectId: 'healthtrack-app-7dc6d',
    authDomain: 'healthtrack-app-7dc6d.firebaseapp.com',
    storageBucket: 'healthtrack-app-7dc6d.firebasestorage.app',
    measurementId: 'G-RBWMMB1M01',
  );
}
